### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by jaroslaw-hill** [what-studio/gauge#1]
HI All,
I was trying to use the gauge, but I found some problem during installation on Windows7 from **gauge-0.4.1.tar.gz**
after calling **setup.py install** I got 

**constants.c**
C:\Users\jaroslaw.hill\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python27\libs
/LIBPATH:C:\Python27\PCbuild /EXPORT:initconstants build\temp.win32-2.7\Release\
gauge/constants.obj /OUT:build\lib.win32-2.7\gauge\constants.pyd /IMPLIB:build\temp.win32-2.7\Release\gauge\constants.lib /MANIFESTFILE:build\temp.win32-2.7\Release\gauge\constants.pyd.manifest
   Creating library build\temp.win32-2.7\Release\gauge\constants.lib and object
build\temp.win32-2.7\Release\gauge\constants.exp
building 'gauge.core' extension
C:\Users\jaroslaw.hill\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcgauge/core.c /Fobuild\temp.win32-2.7\Release\gauge/core.obj

**core.c**
gauge/core.c(1305) : error C2433: '__pyx_f_5gauge_9constants_CLASS_NAME' : 'inline' not permitted on data declarations
gauge/core.c(2422) : error C2440: 'type cast' : cannot convert from '__pyx_ctuple_double__and_double' to '__pyx_ctuple_double__and_double'
gauge/core.c(2422) : error C2198: '__pyx_pf_5gauge_4core_5Gauge_4base_2__set__'
: too few arguments for call

when I tried to do the same, but from **gauge-0.4.1.zip**, I got different problem

 Traceback (most recent call last):
  File "D:\tools\2install\Python\gauge-0.4.1\setup.py", line 51, in <module>
    from Cython.Build import cythonize
**ImportError: No module named Cython.Build**

Did I make a mistake somewhere or is there any different way to install the gauge?

Best Regards

**Comment by sublee** [comment]
Would you try `pip install cython` before `python setup.py install` in `gauge-0.4.1.zip`?

**Comment by jaroslaw-hill** [comment]
Hi,
I installed cython successfully, but next trial with gauge-0.4.1.zip gave
me the same what gauge-0.4.1.tar.gz returns

Compiling gauge/constants.pyx because it changed.
Compiling gauge/core.pyx because it changed.
Compiling gauge/deterministic.pyx because it changed.
[1/3] Cythonizing gauge/constants.pyx
warning: gauge\constants.pxd:13:26: Declarations should not be declared
inline.
[2/3] Cythonizing gauge/core.pyx
warning: gauge\constants.pxd:13:26: Declarations should not be declared
inline.
[3/3] Cythonizing gauge/deterministic.pyx
warning: gauge\constants.pxd:13:26: Declarations should not be declared
inline.
running install
running bdist_egg
running egg_info
creating gauge.egg-info
writing requirements to gauge.egg-info\requires.txt
writing gauge.egg-info\PKG-INFO
writing top-level names to gauge.egg-info\top_level.txt
writing dependency_links to gauge.egg-info\dependency_links.txt
writing manifest file 'gauge.egg-info\SOURCES.txt'
reading manifest file 'gauge.egg-info\SOURCES.txt'
writing manifest file 'gauge.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib.win32-2.7
creating build\lib.win32-2.7\gauge
copying gauge\__about__.py -> build\lib.win32-2.7\gauge
copying gauge\__init__.py -> build\lib.win32-2.7\gauge
running build_ext
building 'gauge.constants' extension
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\gauge
C:\Users\jaroslaw.hill\AppData\Local\Programs\Common\Microsoft\Visual C++
for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
-IC:\Python27\include -IC:\Python27\PC /Tcgauge/constants.c
/Fobuild\temp.win32-2.7\Release\gauge/constants.obj

constants.c
C:\Users\jaroslaw.hill\AppData\Local\Programs\Common\Microsoft\Visual C++
for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO
/LIBPATH:C:\Python27\libs
/LIBPATH:C:\Python27\PCbuild /EXPORT:initconstants
build\temp.win32-2.7\Release\
gauge/constants.obj /OUT:build\lib.win32-2.7\gauge\constants.pyd
/IMPLIB:build\temp.win32-2.7\Release\gauge\constants.lib
/MANIFESTFILE:build\temp.win32-2.7\Release\gauge\constants.pyd.manifest
   Creating library build\temp.win32-2.7\Release\gauge\constants.lib and
object
build\temp.win32-2.7\Release\gauge\constants.exp
building 'gauge.core' extension
C:\Users\jaroslaw.hill\AppData\Local\Programs\Common\Microsoft\Visual C++
for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG
-IC:\Python27\include -IC:\Python27\PC /Tcgauge/core.c
/Fobuild\temp.win32-2.7\Release\gauge/core.obj

core.c
gauge/core.c(1362) : error C2433: '__pyx_f_5gauge_9constants_CLASS_NAME' :
'inline' not permitted on data declarations
gauge/core.c(2504) : error C2440: 'type cast' : cannot convert from
'__pyx_ctuple_double__and_double' to __pyx_ctuple_double__and_double'
gauge/core.c(2504) : error C2198:
'__pyx_pf_5gauge_4core_5Gauge_4base_2__set__'
: too few arguments for call
error: command
'C:\\Users\\jaroslaw.hill\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual
C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

Pozdrawiam
Jarosław Hill

2017-08-18 3:32 GMT+02:00 Heungsub Lee <notifications@github.com>:

**Comment by sublee** [comment]
I don't develop a Python project on Windows, so I don't have an idea to fix your issue currently.

Anyway, what's your use case?  I wonder because the `gauge` library is not well published yet.  There's neither documentation nor advertisement.

**Comment by jaroslaw-hill** [comment]
This is not the issue any more since I install Linux and run the library under it.
I was looking for gauge libraries developed in Python and because I didn't find any graphical examples I decided to run the gauge from the sources, that was the way I had to ask for your help.
One more time Thank you very much for quick and good responses.
